### ISSUE TITLE
Issue with "limited" accounts

### ISSUE THREAD

**Issue by volodymyrzuyev** [Rudokhvist/ItemDispenser#8]
The plugin does not accept trades on accounts that are "limited" (Steam community market is not unlocked). Is it user error? Or is it a limitation of ASF? 
Thanks

**Comment by Rudokhvist** [comment]
Yes, it's a limitation of ASF, in a way. ASF uses api key to detect new notifications, including notifications about new trades. On limitead accounts there is no api key, so it's impossible to get those notifications via steam API. Technically it's still possible to fetch notifications by parsing html, or just check for new trades periodically, but since ASF's main purpose is to farm trading cards, and limited accounts don't drop any, nobody ever bothered to implement those "hacky" ways just for limited accounts.
